Repository xadamxk/HFX2.0, pull requests merged in 2019-10, with the labels that each got.

#34 Fix issues with settings
  src/_core/Feature.js
  src/_core/Logger.js
  src/_core/Settings.js
  src/_core/Util.js
  src/modules/global/Alerts.js
Labels: Type: Bug

#36 Allow Multiple Paths for Sections
  src/_core/Section.js
Labels: Type: Enhancement

#39 Feature/implement background page
  assets/css/options.css
  assets/js/background.js
  assets/js/options.js
  assets/pages/options.html
  manifest.json
  src/_core/Feature.js
  src/_core/HFX.js
  src/_core/Section.js
  src/_core/Settings.js
  src/_core/Storage.js
  src/_core/Util.js
  src/modules/game/MedalOfHonorTracker.js
  src/modules/global/Alerts.js
Labels: Category: Framework, Type: Enhancement

#43 Rework Storage Structure
  assets/css/HFX.css
  assets/js/background.js
  assets/js/options.js
  manifest.json
  src/_core/Feature.js
  src/_core/Settings.js
  src/_core/Storage.js
  src/_core/Util.js
  src/modules/game/BatteryAbsoluteTime.js
  src/modules/game/BatteryPercent.js
  src/modules/game/MedalOfHonorTracker.js
  src/modules/game/ShortcutLeaderboard.js
  src/modules/game/ShortcutLogs.js
  src/modules/global/Alerts.js
  src/modules/global/ChangeBodyColor.js
  src/modules/global/CollapsePossiblyRelatedThreads.js
  src/modules/global/HideImages.js
  src/modules/pms/TrackingLinks.js
  src/modules/threads/ExpandBlockedPosts.js
  src/modules/threads/HideBlockedPosts.js
  src/modules/threads/PMFromPost.js
Labels: Category: Framework, Type: Enhancement

#44 Fix Spinner Hiding
  assets/js/options.js
Labels: Type: Bug

#46 Feature/new feature section templating
  gulpfile.js
  package.json
  templates/Feature.js
  templates/Section.js
  templates/index.js
  templates/prompt.js
  yarn.lock
Labels: Category: Framework, Type: Enhancement

#47 Feature/refactor pm from post
  .editorconfig
  .eslintrc.json
  extension/assets/css/HFX.css
  extension/assets/css/font-awesome.min.css
  extension/assets/css/titatoggle-dist-min.css
  extension/assets/css/xbbcode.css
  extension/assets/dependencies/Chart.bundle.min.js
  extension/assets/dependencies/infinite-scroll.pkgd.min.js
  extension/assets/dependencies/jquery.sticky.js
  extension/assets/dependencies/jquery.tinybox.js
  extension/assets/dependencies/jscolor.js
  extension/assets/dependencies/xbbcode.js
  extension/assets/js/old_options.js
  extension/assets/pages/old_options.html
  extension/assets/pages/popup.html
  src/features/threads/PMFromPost.js
Labels: Category: Threads, Type: Enhancement

#48 Feature/start unit tests
  .eslintrc.json
  package.json
  src/core/Logger.js
  tests/core/Logger.test.js
  yarn.lock
Labels: Category: Framework

#49 Feature/reputation charts
  .eslintrc.json
  extension/assets/js/options.js
  extension/manifest.json
  gulpfile.js
  package.json
  src/features/reputation/RepCharts.js
  src/sections/Reputation.js
  templates/Feature.js
  templates/Section.js
  yarn.lock
Labels: Category: Reputation, Type: Enhancement
